### PR TITLE
Fixed duplicate image in iOS 13

### PR DESCRIPTION
**Pull request by dragomir-ivanov-212**

### CODE REVIEW

**Comment by smurfy** [comment]
Works like a charm

**Comment by thermech** [comment]
I can still reproduce the problem. For exemple after closing the native iOS "share" (UIActivityViewController) on iOS 13

**Comment by thermech** [comment]
We propose this solution https://github.com/sochalewski/UIImageViewAlignedSwift/pull/29

**Comment by dragomir-ivanov-212** [comment]
> @thermech 
I can still reproduce the problem. For exemple after closing the native iOS "share" (UIActivityViewController) on iOS 13

Overriding `tintColorDidChange` fixed that. But you're right to subclass UIView instead, as we don't know what could change with UIImageView. 
Closing this PR in favour of #29

**Pull request closed without merging**
